version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - TZ=UTC
    volumes:
      - ./docker-volume/mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
