server:
  port: 8081

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/local/schema.sql
      data-locations: classpath*:sql/local/data.sql

  r2dbc:
    url: r2dbc:mysql://localhost:3306/chat
    username: root
    password: local

  data:
    r2dbc:
      repositories:
        enabled: true
