server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${RDB_DRIVER}
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: ${JWT_SECRET}
  atkTTL: ${JWT_ATK_TTL} # sec
  rtkTTL: ${JWT_RTK_TTL} # sec
