spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/test/schema.sql
      data-locations: classpath*:sql/test/data.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

token:
  secret: testTokenSecret
  atkTTL: 0
  rtkTTL: 0

logging:
  level:
    sql: trace
