server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: test
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/test/schema.sql
      data-locations: classpath*:sql/test/data.sql

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    sql: trace
